# Generated by Django 6.0.5 on 2026-05-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('WARNING_80', '80% Budget Used'), ('EXHAUSTED', 'Budget Exhausted'), ('SYSTEM', 'System Alert')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='budgets.budgetcycle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
