# Generated by Django 6.0.5 on 2026-05-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transportation'), ('SHOPPING', 'Shopping'), ('BILLS', 'Bills & Utilities'), ('ENTERTAINMENT', 'Entertainment'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budgets.budgetcycle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
